In [25]:
current_score_df = match_delivery.groupby(
    'match_id'
).cumsum()['total_runs']

match_delivery['current_score'] = current_score_df

TypeError: dtype 'str' does not support operation 'cumsum'

In [26]:
print(match_delivery.dtypes)

match_id            int64
inning              int64
batting_team          str
bowling_team          str
over                int64
ball                int64
batter                str
bowler                str
non_striker           str
batsman_runs        int64
extra_runs          int64
total_runs          int64
extras_type           str
is_wicket           int64
player_dismissed    int64
dismissal_kind        str
fielder               str
id                  int64
winner                str
target              int64
wickets_left        int64
dtype: object

In [27]:
print(match_delivery.head())

     match_id  inning                 batting_team           bowling_team  \
124    335982       2  Royal Challengers Bangalore  Kolkata Knight Riders
125    335982       2  Royal Challengers Bangalore  Kolkata Knight Riders
126    335982       2  Royal Challengers Bangalore  Kolkata Knight Riders
127    335982       2  Royal Challengers Bangalore  Kolkata Knight Riders
128    335982       2  Royal Challengers Bangalore  Kolkata Knight Riders

     over  ball    batter    bowler non_striker  batsman_runs  ...  \
124     0     1  R Dravid  AB Dinda    W Jaffer             1  ...
125     0     2  W Jaffer  AB Dinda    R Dravid             0  ...
126     0     3  W Jaffer  AB Dinda    R Dravid             0  ...
127     0     4  W Jaffer  AB Dinda    R Dravid             1  ...
128     0     5  R Dravid  AB Dinda    W Jaffer             1  ...

     total_runs  extras_type is_wicket  player_dismissed  dismissal_kind  \
124           1          NaN         0                 0             NaN
125           1        wides         0                 0             NaN
126           0          NaN         0                 0             NaN
127           1          NaN         0                 0             NaN
128           1          NaN         0                 0             NaN

    fielder      id                 winner target  wickets_left
124     NaN  335982  Kolkata Knight Riders    222            10
125     NaN  335982  Kolkata Knight Riders    222            10
126     NaN  335982  Kolkata Knight Riders    222            10
127     NaN  335982  Kolkata Knight Riders    222            10
128     NaN  335982  Kolkata Knight Riders    222            10

[5 rows x 21 columns]

In [ ]:
final_df.head()

In [28]:
groupby(... )['total_runs'].cumsum()

NameError: name 'groupby' is not defined

In [ ]:
final_df.head()

In [29]:
match_delivery['current_score'] = (
    match_delivery
    .groupby('match_id')['total_runs']
    .cumsum()
)

In [ ]:
final_df.head()

In [30]:
groupby(... )['total_runs'].cumsum()

NameError: name 'groupby' is not defined

In [31]:
match_delivery['current_score'] = (
    match_delivery
    .groupby('match_id')['total_runs']
    .cumsum()
)

In [32]:
match_delivery[['total_runs', 'current_score']].head()

     total_runs  current_score
124           1              1
125           1              2
126           0              2
127           1              3
128           1              4

In [33]:
match_delivery['runs_left'] = (
    match_delivery['target']
    - match_delivery['current_score']
)

In [34]:
match_delivery['balls_left'] = (
    120 - (
        (match_delivery['over'] - 1) * 6
        + match_delivery['ball']
    )
)

In [35]:
print(match_delivery.columns)

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'winner', 'target', 'wickets_left',
       'current_score', 'runs_left', 'balls_left'],
      dtype='str')

In [37]:
match_delivery['current_run_rate'] = (
    match_delivery['current_score'] * 6
) / (
    120 - match_delivery['balls_left']
)

In [38]:
match_delivery['required_run_rate'] = (
    match_delivery['runs_left'] * 6
) / (
    match_delivery['balls_left']
)

In [39]:
match_delivery['result'] = (
    match_delivery['batting_team']
    == match_delivery['winner']
).astype(int)

In [40]:
print(match_delivery.columns)

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'winner', 'target', 'wickets_left',
       'current_score', 'runs_left', 'balls_left', 'current_run_rate',
       'required_run_rate', 'result'],
      dtype='str')

In [41]:
print(match_delivery.columns)

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'winner', 'target', 'wickets_left',
       'current_score', 'runs_left', 'balls_left', 'current_run_rate',
       'required_run_rate', 'result'],
      dtype='str')

In [42]:
final_df = match_delivery[
    [
        'batting_team',
        'bowling_team',
        'runs_left',
        'balls_left',
        'wickets_left',
        'target',
        'current_run_rate',
        'required_run_rate',
        'result'
    ]
]

In [43]:
final_df.head()

,batting_team,bowling_team,runs_left,balls_left,wickets_left,target,current_run_rate,required_run_rate,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,221,125,10,222,-1.2,10.608000,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,220,124,10,222,-3.0,10.645161,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,220,123,10,222,-4.0,10.731707,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,219,122,10,222,-9.0,10.770492,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,218,121,10,222,-24.0,10.809917,0

In [44]:
print(final_df.shape)

(125741, 9)

In [45]:
print(final_df.isnull().sum())

batting_team          0
bowling_team          0
runs_left             0
balls_left            0
wickets_left          0
target                0
current_run_rate     35
required_run_rate     0
result                0
dtype: int64

In [46]:
final_df = final_df.dropna()

In [47]:
print(final_df.isnull().sum())

batting_team         0
bowling_team         0
runs_left            0
balls_left           0
wickets_left         0
target               0
current_run_rate     0
required_run_rate    0
result               0
dtype: int64

In [48]:
final_df.to_csv("../data/final_df.csv", index=False)

In [49]:
final_df.head()

,batting_team,bowling_team,runs_left,balls_left,wickets_left,target,current_run_rate,required_run_rate,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,221,125,10,222,-1.2,10.608000,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,220,124,10,222,-3.0,10.645161,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,220,123,10,222,-4.0,10.731707,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,219,122,10,222,-9.0,10.770492,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,218,121,10,222,-24.0,10.809917,0

In [50]:
print(final_df.shape)

(125706, 9)

In [51]:
print(final_df.isnull().sum())

batting_team         0
bowling_team         0
runs_left            0
balls_left           0
wickets_left         0
target               0
current_run_rate     0
required_run_rate    0
result               0
dtype: int64

In [52]:
final_df.to_csv("../data/final_df.csv", index=False)

In [53]:
current_run_rate = (current_score * 6) / (120 - balls_left)

NameError: name 'current_score' is not defined

In [54]:
import numpy as np

print(final_df.isin([np.inf, -np.inf]).sum())

batting_team            0
bowling_team            0
runs_left               0
balls_left              0
wickets_left            0
target                  0
current_run_rate     1057
required_run_rate       0
result                  0
dtype: int64

In [55]:
import numpy as np

final_df.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

,batting_team,bowling_team,runs_left,balls_left,wickets_left,target,current_run_rate,required_run_rate,result
124,Royal Challengers Bangalore,Kolkata Knight Riders,221,125,10,222,-1.200000,10.608000,0
125,Royal Challengers Bangalore,Kolkata Knight Riders,220,124,10,222,-3.000000,10.645161,0
126,Royal Challengers Bangalore,Kolkata Knight Riders,220,123,10,222,-4.000000,10.731707,0
127,Royal Challengers Bangalore,Kolkata Knight Riders,219,122,10,222,-9.000000,10.770492,0
128,Royal Challengers Bangalore,Kolkata Knight Riders,218,121,10,222,-24.000000,10.809917,0
...,...,...,...,...,...,...,...,...,...
260915,Kolkata Knight Riders,Sunrisers Hyderabad,3,67,8,113,12.452830,0.268657,1
260916,Kolkata Knight Riders,Sunrisers Hyderabad,2,66,8,113,12.333333,0.181818,1
260917,Kolkata Knight Riders,Sunrisers Hyderabad,1,65,8,113,12.218182,0.092308,1
260918,Kolkata Knight Riders,Sunrisers Hyderabad,0,64,8,113,12.107143,0.000000,1
260919,Kolkata Knight Riders,Sunrisers Hyderabad,-1,63,8,113,12.000000,-0.095238,1

In [56]:
final_df.dropna(inplace=True)

In [57]:
print(final_df.isnull().sum())

batting_team         0
bowling_team         0
runs_left            0
balls_left           0
wickets_left         0
target               0
current_run_rate     0
required_run_rate    0
result               0
dtype: int64

In [58]:
print(final_df.isin([np.inf, -np.inf]).sum())

batting_team         0
bowling_team         0
runs_left            0
balls_left           0
wickets_left         0
target               0
current_run_rate     0
required_run_rate    0
result               0
dtype: int64

In [59]:
final_df.to_csv("../data/final_df.csv", index=False)

python src/train_model.py