In [27]:
import pandas as pd

In [26]:
matches=matches['winner'].isnull().sum()

IndexError: invalid index to scalar variable.

In [35]:
print(matches)

           id   season        city        date   match_type  player_of_match  \
0      335982  2007/08   Bangalore  2008-04-18       League      BB McCullum
1      335983  2007/08  Chandigarh  2008-04-19       League       MEK Hussey
2      335984  2007/08       Delhi  2008-04-19       League      MF Maharoof
3      335985  2007/08      Mumbai  2008-04-20       League       MV Boucher
4      335986  2007/08     Kolkata  2008-04-20       League        DJ Hussey
...       ...      ...         ...         ...          ...              ...
1090  1426307     2024   Hyderabad  2024-05-19       League  Abhishek Sharma
1091  1426309     2024   Ahmedabad  2024-05-21  Qualifier 1         MA Starc
1092  1426310     2024   Ahmedabad  2024-05-22   Eliminator         R Ashwin
1093  1426311     2024     Chennai  2024-05-24  Qualifier 2    Shahbaz Ahmed
1094  1426312     2024     Chennai  2024-05-26        Final         MA Starc

                                                  venue  \
0                                 M Chinnaswamy Stadium
1            Punjab Cricket Association Stadium, Mohali
2                                      Feroz Shah Kotla
3                                      Wankhede Stadium
4                                          Eden Gardens
...                                                 ...
1090  Rajiv Gandhi International Stadium, Uppal, Hyd...
1091                   Narendra Modi Stadium, Ahmedabad
1092                   Narendra Modi Stadium, Ahmedabad
1093           MA Chidambaram Stadium, Chepauk, Chennai
1094           MA Chidambaram Stadium, Chepauk, Chennai

                            team1                        team2  \
0     Royal Challengers Bangalore        Kolkata Knight Riders
1                 Kings XI Punjab          Chennai Super Kings
2                Delhi Daredevils             Rajasthan Royals
3                  Mumbai Indians  Royal Challengers Bangalore
4           Kolkata Knight Riders              Deccan Chargers
...                           ...                          ...
1090                 Punjab Kings          Sunrisers Hyderabad
1091          Sunrisers Hyderabad        Kolkata Knight Riders
1092  Royal Challengers Bengaluru             Rajasthan Royals
1093          Sunrisers Hyderabad             Rajasthan Royals
1094          Sunrisers Hyderabad        Kolkata Knight Riders

                      toss_winner toss_decision                       winner  \
0     Royal Challengers Bangalore         field        Kolkata Knight Riders
1             Chennai Super Kings           bat          Chennai Super Kings
2                Rajasthan Royals           bat             Delhi Daredevils
3                  Mumbai Indians           bat  Royal Challengers Bangalore
4                 Deccan Chargers           bat        Kolkata Knight Riders
...                           ...           ...                          ...
1090                 Punjab Kings           bat          Sunrisers Hyderabad
1091          Sunrisers Hyderabad           bat        Kolkata Knight Riders
1092             Rajasthan Royals         field             Rajasthan Royals
1093             Rajasthan Royals         field          Sunrisers Hyderabad
1094          Sunrisers Hyderabad           bat        Kolkata Knight Riders

       result  result_margin  target_runs  target_overs super_over method  \
0        runs          140.0        223.0          20.0          N    NaN
1        runs           33.0        241.0          20.0          N    NaN
2     wickets            9.0        130.0          20.0          N    NaN
3     wickets            5.0        166.0          20.0          N    NaN
4     wickets            5.0        111.0          20.0          N    NaN
...       ...            ...          ...           ...        ...    ...
1090  wickets            4.0        215.0          20.0          N    NaN
1091  wickets            8.0        160.0          20.0          N    NaN
1092  wickets            4.0        173.0          20.0          N    NaN
1093     runs           36.0        176.0          20.0          N    NaN
1094  wickets            8.0        114.0          20.0          N    NaN

                    umpire1               umpire2
0                 Asad Rauf           RE Koertzen
1                 MR Benson            SL Shastri
2                 Aleem Dar        GA Pratapkumar
3                  SJ Davis             DJ Harper
4                 BF Bowden           K Hariharan
...                     ...                   ...
1090            Nitin Menon             VK Sharma
1091           AK Chaudhary              R Pandit
1092  KN Ananthapadmanabhan  MV Saidharshan Kumar
1093            Nitin Menon             VK Sharma
1094          J Madanagopal           Nitin Menon

[1090 rows x 20 columns]

In [38]:
matches=matches.dropna(subset=['winner'])

In [39]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [41]:
matches['team2'].unique()

<StringArray>
[      'Kolkata Knight Riders',         'Chennai Super Kings',
            'Rajasthan Royals', 'Royal Challengers Bangalore',
             'Deccan Chargers',             'Kings XI Punjab',
            'Delhi Daredevils',              'Mumbai Indians',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',     'Rising Pune Supergiants',
               'Gujarat Lions',      'Rising Pune Supergiant',
              'Delhi Capitals',                'Punjab Kings',
              'Gujarat Titans',        'Lucknow Super Giants',
 'Royal Challengers Bengaluru']
Length: 19, dtype: str

In [40]:
matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [101]:
matches_df["team1"].unique()

<StringArray>
['Royal Challengers Bangalore',                'Punjab Kings',
              'Delhi Capitals',              'Mumbai Indians',
       'Kolkata Knight Riders',            'Rajasthan Royals',
             'Deccan Chargers',         'Chennai Super Kings',
        'Kochi Tuskers Kerala',               'Pune Warriors',
         'Sunrisers Hyderabad',               'Gujarat Lions',
     'Rising Pune Supergiants',      'Rising Pune Supergiant',
        'Lucknow Super Giants',              'Gujarat Titans',
 'Royal Challengers Bengaluru']
Length: 17, dtype: str

In [100]:
matches_df.replace('Delhi Daredevils','Delhi Capitals',inplace=True)

,city,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals
3,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders
...,...,...,...,...,...,...
1090,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad
1091,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders
1092,Ahmedabad,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
1093,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad
1094,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders

In [99]:
matches_df.replace('Kings XI Punjab','Punjab Kings',inplace=True)

,city,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders
...,...,...,...,...,...,...
1090,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad
1091,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders
1092,Ahmedabad,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
1093,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad
1094,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders

In [32]:
matches.shape

(1095, 20)

In [24]:
type(matches)

numpy.int64

In [37]:
print(matches.shape)

(1090, 20)

In [63]:
print(matches_df)

       season        city                        team1  \
0     2007/08   Bangalore  Royal Challengers Bangalore
1     2007/08  Chandigarh              Kings XI Punjab
2     2007/08       Delhi             Delhi Daredevils
3     2007/08      Mumbai               Mumbai Indians
4     2007/08     Kolkata        Kolkata Knight Riders
...       ...         ...                          ...
1090     2024   Hyderabad                 Punjab Kings
1091     2024   Ahmedabad          Sunrisers Hyderabad
1092     2024   Ahmedabad  Royal Challengers Bengaluru
1093     2024     Chennai          Sunrisers Hyderabad
1094     2024     Chennai          Sunrisers Hyderabad

                            team2                  toss_winner toss_decision  \
0           Kolkata Knight Riders  Royal Challengers Bangalore         field
1             Chennai Super Kings          Chennai Super Kings           bat
2                Rajasthan Royals             Rajasthan Royals           bat
3     Royal Challengers Bangalore               Mumbai Indians           bat
4                 Deccan Chargers              Deccan Chargers           bat
...                           ...                          ...           ...
1090          Sunrisers Hyderabad                 Punjab Kings           bat
1091        Kolkata Knight Riders          Sunrisers Hyderabad           bat
1092             Rajasthan Royals             Rajasthan Royals         field
1093             Rajasthan Royals             Rajasthan Royals         field
1094        Kolkata Knight Riders          Sunrisers Hyderabad           bat

      target_runs  target_overs                       winner
0           223.0          20.0        Kolkata Knight Riders
1           241.0          20.0          Chennai Super Kings
2           130.0          20.0             Delhi Daredevils
3           166.0          20.0  Royal Challengers Bangalore
4           111.0          20.0        Kolkata Knight Riders
...           ...           ...                          ...
1090        215.0          20.0          Sunrisers Hyderabad
1091        160.0          20.0        Kolkata Knight Riders
1092        173.0          20.0             Rajasthan Royals
1093        176.0          20.0          Sunrisers Hyderabad
1094        114.0          20.0        Kolkata Knight Riders

[1095 rows x 9 columns]

In [70]:
matches_df[["city","team1",
"team2",
"toss_winner",
"toss_decision",
"winner"]]

,city,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders
...,...,...,...,...,...,...
1090,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad
1091,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders
1092,Ahmedabad,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
1093,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad
1094,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders

In [74]:
matches_df.head()

,city,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders

In [75]:
matches_df.isnull().sum()

city             51
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            5
dtype: int64

In [76]:
matches_df.shape

(1095, 6)

In [68]:
print(matches_df)

            city                        team1                        team2  \
0      Bangalore  Royal Challengers Bangalore        Kolkata Knight Riders
1     Chandigarh              Kings XI Punjab          Chennai Super Kings
2          Delhi             Delhi Daredevils             Rajasthan Royals
3         Mumbai               Mumbai Indians  Royal Challengers Bangalore
4        Kolkata        Kolkata Knight Riders              Deccan Chargers
...          ...                          ...                          ...
1090   Hyderabad                 Punjab Kings          Sunrisers Hyderabad
1091   Ahmedabad          Sunrisers Hyderabad        Kolkata Knight Riders
1092   Ahmedabad  Royal Challengers Bengaluru             Rajasthan Royals
1093     Chennai          Sunrisers Hyderabad             Rajasthan Royals
1094     Chennai          Sunrisers Hyderabad        Kolkata Knight Riders

                      toss_winner toss_decision                       winner
0     Royal Challengers Bangalore         field        Kolkata Knight Riders
1             Chennai Super Kings           bat          Chennai Super Kings
2                Rajasthan Royals           bat             Delhi Daredevils
3                  Mumbai Indians           bat  Royal Challengers Bangalore
4                 Deccan Chargers           bat        Kolkata Knight Riders
...                           ...           ...                          ...
1090                 Punjab Kings           bat          Sunrisers Hyderabad
1091          Sunrisers Hyderabad           bat        Kolkata Knight Riders
1092             Rajasthan Royals         field             Rajasthan Royals
1093             Rajasthan Royals         field          Sunrisers Hyderabad
1094          Sunrisers Hyderabad           bat        Kolkata Knight Riders

[1095 rows x 6 columns]

In [52]:
matches_df=matches_df.fillna({"city": "unknown"})

In [50]:
deliveries = pd.read_csv("../data/deliveries.csv")

In [87]:
matches_df.isnull().sum()

city             51
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            0
dtype: int64

In [49]:
matches=pd.read_csv("../data/matches.csv")

In [84]:
matches_df = matches_df.dropna(subset=["winner"])

In [83]:
matches_df.isnull().sum()

city             51
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            5
dtype: int64

In [97]:
matches_df.isnull().sum()

city             0
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
dtype: int64

In [98]:
matches_df.value_counts()

city        team1                        team2                  toss_winner          toss_decision  winner
Bangalore   Royal Challengers Bangalore  Mumbai Indians         Mumbai Indians       field          Mumbai Indians           5
Mumbai      Mumbai Indians               Delhi Daredevils       Delhi Daredevils     field          Mumbai Indians           4
                                         Kolkata Knight Riders  Mumbai Indians       field          Mumbai Indians           4
Kolkata     Kolkata Knight Riders        Rajasthan Royals       Rajasthan Royals     field          Rajasthan Royals         4
Chandigarh  Kings XI Punjab              Rajasthan Royals       Rajasthan Royals     field          Kings XI Punjab          4
                                                                                                                            ..
Hyderabad   Punjab Kings                 Sunrisers Hyderabad    Punjab Kings         bat            Sunrisers Hyderabad      1
Ahmedabad   Sunrisers Hyderabad          Kolkata Knight Riders  Sunrisers Hyderabad  bat            Kolkata Knight Riders    1
            Royal Challengers Bengaluru  Rajasthan Royals       Rajasthan Royals     field          Rajasthan Royals         1
Chennai     Sunrisers Hyderabad          Rajasthan Royals       Rajasthan Royals     field          Sunrisers Hyderabad      1
                                         Kolkata Knight Riders  Sunrisers Hyderabad  bat            Kolkata Knight Riders    1
Name: count, Length: 917, dtype: int64

In [96]:
matches_df.fillna({"city": "Unknown"})

,city,team1,team2,toss_winner,toss_decision,winner
0,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders
1,Chandigarh,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
2,Delhi,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils
3,Mumbai,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore
4,Kolkata,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders
...,...,...,...,...,...,...
1090,Hyderabad,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad
1091,Ahmedabad,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders
1092,Ahmedabad,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
1093,Chennai,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad
1094,Chennai,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders

            city                        team1                        team2  \
0      Bangalore  Royal Challengers Bangalore        Kolkata Knight Riders
1     Chandigarh              Kings XI Punjab          Chennai Super Kings
2          Delhi             Delhi Daredevils             Rajasthan Royals
3         Mumbai               Mumbai Indians  Royal Challengers Bangalore
4        Kolkata        Kolkata Knight Riders              Deccan Chargers
...          ...                          ...                          ...
1090   Hyderabad                 Punjab Kings          Sunrisers Hyderabad
1091   Ahmedabad          Sunrisers Hyderabad        Kolkata Knight Riders
1092   Ahmedabad  Royal Challengers Bengaluru             Rajasthan Royals
1093     Chennai          Sunrisers Hyderabad             Rajasthan Royals
1094     Chennai          Sunrisers Hyderabad        Kolkata Knight Riders

                      toss_winner toss_decision                       winner
0     Royal Challengers Bangalore         field        Kolkata Knight Riders
1             Chennai Super Kings           bat          Chennai Super Kings
2                Rajasthan Royals           bat             Delhi Daredevils
3                  Mumbai Indians           bat  Royal Challengers Bangalore
4                 Deccan Chargers           bat        Kolkata Knight Riders
...                           ...           ...                          ...
1090                 Punjab Kings           bat          Sunrisers Hyderabad
1091          Sunrisers Hyderabad           bat        Kolkata Knight Riders
1092             Rajasthan Royals         field             Rajasthan Royals
1093             Rajasthan Royals         field          Sunrisers Hyderabad
1094          Sunrisers Hyderabad           bat        Kolkata Knight Riders

[1090 rows x 6 columns]